on: 
  workflow_dispatch: 
  pull_request: {}
  push:
    branches:
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 00 5 1 * *
name: Semgrep
jobs:
  buildmavenDepTree: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Dependency Tree
        run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt -Dmaven.test.skip=true
      - name: Create Zip File
        run: find . -type f -name 'maven_dep_tree.txt' -exec zip -r archive.zip {} +
      - name: Upload Dependency Zip    
        uses: actions/upload-artifact@v3
        with:
          name: zipfile
          path: archive.zip
  semgrep:
    needs: buildmavenDepTree
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      SEMGREP_API_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from previous job 2
        uses: actions/download-artifact@v3
        with:
          name: zipfile    
      - name: Semgrep Scan  
        run: |
          tags=$(curl -s -H "Accept: application/vnd.github.mercy-preview+json" \
               -H "Authorization: token $GH_ACCESS_TOKEN" \
               "https://api.github.com/repos/$GITHUB_REPOSITORY/topics" | jq '.names')
          
          echo $tags
          
          DEPLOYMENT_SLUG=$(curl -s \
               -H "Authorization: Bearer $SEMGREP_API_TOKEN" \
               -H "Content-Type: application/json" \
               "https://semgrep.dev/api/v1/deployments" | jq -r '.deployments[0].slug')
          
          echo $DEPLOYMENT_SLUG
          
          curl -X PUT \
               -H "Authorization: Bearer $SEMGREP_API_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"tags\": $tags}" \
               "https://semgrep.dev/api/v1/deployments/$DEPLOYMENT_SLUG/projects/$GITHUB_REPOSITORY/tags"
          unzip -o archive.zip
          semgrep ci


